/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package iterator_demo;

public class App {

    public static void main(String[] args) {
        
        NumberList numberList = new NumberList();

        for (Iterator iter = numberList.getIterator(); iter.hasNext();){
            int num = (int)iter.next();
            System.out.println("Number : " + num);
        }

    }
}
